export { Connection } from './esl/Connection';
export { Event } from './esl/Event';
export { Parser } from './esl/Parser';
export { Server } from './esl/Server';
export { CallDetails } from './interfaces/call-details';
export { EslEvents } from './interfaces/esl-events';
export { ChannelHeaders } from './interfaces/esl-headers';
export { LinksDto, LinkDto, NodesDto, NodeDataDto, NodeSizeDto, NodeDto, NodeMetaDefDto, NodeMediaDefDto, NodeMenuDefDto, NodeRootDefDto, NodeCoordinatesDto, NodeRouteDefDto, CalendarDetailDto, DtmfInputDefinitionDto, AATreeDto, } from './interfaces/auto-attendant.dto';
export { GatewayDto } from './interfaces/gateway.dto';
export { FallbackRouteDto, ExtensionVarsDto, ExtensionParamsDto, ExtensionDto } from './interfaces/extension.dto';
export { GroupDto, GroupUserDto } from './interfaces/group.dto';
export { HolidayCalendarDto, HolidayMessageDto } from './interfaces/holiday-calendar.dto';
export { InboundRuleRouteDto, InboundRuleRouteTypeDto, InboundRuleDto } from './interfaces/inbound-rule.dto';
export { MediaDto } from './interfaces/media.dto';
export { WorkingCalendarDto, WorkingTimeDto } from './interfaces/working-calendar.dto';
export { PLAYBACK_TERMINATOR_ALL, PLAYBACK_TERMINATOR_NONE } from './constants';
export declare function setLogLevel(level: any): void;
export declare const eslSetLogLevel: typeof setLogLevel;
